### PR TITLE
fix(core/render-biblio): sanitize spaces in reference IDs

### LINKED ISSUE #5102: The names of the reference contain spaces
## Description of problem

**URL to affected spec or repo:**

https://w3c.github.io/ruby-tts-req/

**What happened (e.g., it crashed)?:**

When the name of a [reference](https://respec.org/docs/#references-0) contains spaces (like [1](https://github.com/w3c/ruby-tts-req/blob/310c7ffc192406d2f1553513a68bf494948c2d1a/index.html#L80) and [2](https://github.com/w3c/ruby-tts-req/blob/310c7ffc192406d2f1553513a68bf494948c2d1a/index.html#L74)), the generated HTML `id` attribute value will also contain spaces, which violates HTML syntax.

**Expected behavior (e.g., it shouldn't crash):**

Either explicitly prohibit spaces in the names of references, or replace spaces with hyphens/underscores in the generated IDs.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Reference names with spaces (e.g. 'Ruby TTS Req') produced invalid HTML IDs containing spaces. Consolidates all bib- ID generation through a bibRefId() helper that replaces whitespace with hyphens.

Closes #5102

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Hmmm... definitely need a test for this one. 

The examples are wild:

```
	  'Tokyo Ghoul: re': {
              title: "Tokyo Ghoul: re, Vol. 8, Chapter 76 “Daso (惰疎)",
              authors: ["Sui Ishida"], 
              id: "Tokyo Groul: re 8-76",
              date: "2016",
              publisher: "Shueisha",
          },
          'Transliteration Training Course': {
              title: "Textbook for the Volunteer Transliteration Training Course: Basics (In Japanese, 音訳ボランティア養成講習会テキスト　基礎課程編)",
	      href: "https://naiiv-books.net/shopdetail/000000000023/",
            date: "March 2010",
            publisher: "National Council of Japan for the Visually Impaired (In Japanese, 全国視覚障害者情報提供施設協会)",
          },
```

As I never expected ids from bib-ref to be used this way (they follow the short name rules from w3c)... but sure, why not!

**Comment by marcoscaceres** [comment]
@copilot can you add tests. See my comment above?

File: src/core/render-biblio.js [hunk 1]
```diff
@@ -8,6 +8,11 @@ import { html } from "./import-maps.js";
 
 export const name = "core/render-biblio";
 
+/** @param {string} ref */
+function bibRefId(ref) {
+  return `bib-${ref.toLowerCase().replace(/\s+/g, "-")}`;
```
Comment (marcoscaceres) [inline src/core/render-biblio.js]: @copilot, is it enough to just replace spaces? Are there other weird things that could be used for IDs by people that could end up breaking HTML? Should we be more thorough here? 

If yes, can you implement it?

File: src/core/utils.js [hunk 2]
```diff
@@ -393,6 +393,25 @@ export function addHashId(elem, prefix = "") {
...
+/**
+ * Converts a string to a slug suitable for use in an HTML id attribute:
+ * lowercases (unless noLC is true), decomposes Unicode, strips diacritics,
+ * replaces runs of non-word characters with "-", and trims leading/trailing
+ * hyphens.
+ * @param {string} txt
+ * @param {boolean} [noLC] - when true, skip lowercasing
+ * @returns {string}
+ */
+export function toId(txt, noLC = false) {
```
Comment (marcoscaceres) [inline src/core/utils.js:405]: @copilot, as we are adding this new util, you might want to test it pretty thoroughly along with the other exported util functions

**Comment by marcoscaceres** [comment]
@copilot wonderful! But I’m worried toId is to generic a name (and it looks like told)… maybe call it toSafeHTMLId() or something better?

**Review by sidvishnoi — APPROVED** [review]
:shipit:

**Review by sidvishnoi — APPROVED** [review]
GitHub asking for review even when I just did, so, :shipit: again.
