### PR TITLE
fix(core/dfn): prevent adding `data-local-lt` to `data-lt`

### LINKED ISSUE #5007: Local text defined in `data-local-lt` incorrectly copied to `data-lt`
## Description of problem

**URL to affected spec or repo:**

https://w3c.github.io/rdf-concepts/spec/#dfn-rdf-string

**What happened (e.g., it crashed)?:**

Definition defines an additional linking text aimed at local usage in a `data-local-lt` attribute. Source is:

```html
<dfn id="dfn-rdf-string" class="export" data-local-lt="string">RDF string</dfn>
```

The additional linking text ends up appearing in a `data-lt` attribute as well, defeating the purpose of using `data-local-lt` in the first place. Generated HTML:

```html
<dfn id="dfn-rdf-string" class="export" data-local-lt="string"
  data-export="" data-lt="RDF string|string" data-plurals="rdf strings|strings"
  data-dfn-type="dfn">
    RDF string
</dfn>
```

**Expected behavior (e.g., it shouldn't crash):**

The local linking text should not be copied to `data-lt`.

**Optional, steps to reproduce:**

See code example above!

### PR DESCRIPTION
**Pull request by dontcallmedom**
Closes #5007

### CODE REVIEW

File: src/core/dfn.js [hunk 1]
```diff
@@ -71,11 +71,11 @@ export function run() {
     computeType(dfn, linkingText);
     computeExport(dfn);
 
-    // Only add `lt`s that are different from the text content
-    if (titles.length === 1 && linkingText === norm(dfn.textContent)) {
-      continue;
+    // Only add `lt`s that are different from the text content and local-lts
+    const lt = titles.filter(t => !((dfn.dataset.localLt || "").split("|").includes(t)));
```
Comment (sidvishnoi) [inline src/core/dfn.js:75]: Might be a good idea to add a `const localLt` to avoid splitting on each `filter` callback.

Comment (dontcallmedom) [reply src/core/dfn.js]: done in https://github.com/speced/respec/pull/5014/commits/ae73f00da97d1c5dd11a7637ed7937078274c320

File: src/core/dfn.js [hunk 2]
```diff
@@ -71,11 +71,12 @@ export function run() {
     computeType(dfn, linkingText);
     computeExport(dfn);
 
-    // Only add `lt`s that are different from the text content
-    if (titles.length === 1 && linkingText === norm(dfn.textContent)) {
-      continue;
+    // Only add `lt`s that are different from the text content and local-lts
+    const localLt = (dfn.dataset.localLt || "").split("|");
```
Comment (tidoust) [inline src/core/dfn.js:75]: `getDfnTitles` calls `norm` on individual entries to trim spaces. Since you're going to compare strings, that seems needed as well?

 ```suggestion
    const localLt = (dfn.dataset.localLt || "").split("|").map(norm);
```

**Comment by sidvishnoi** [comment]
(Ignore failing tests about History, some rate limiting issue likely)
