### PR TITLE
fix(core/xref): normalize versioned spec names in data-cite context

### LINKED ISSUE #5224: Same spec version resolution mess
## Description of problem

Weird bug;

```HTML
        <p>
          <a data-cite="SERVICE-WORKERS-1#scope-match-algorithm">Service
          Workers</a>. 
        </p>
         <aside class="note" data-cite="service-workers">
           [=service worker=]
          </aside>
```
Gives: 

> Couldn't find "service worker" in this document or other cited documents: [csp3], [dom], [encoding], [fetch], [html], [image-resource], [infra], [mediaqueries-5], [mimesniff], [screen-orientation], [url], and [webidl].
How to fix: [See search matches for "service worker"](https://respec.org/xref/?term=service+worker&types=_CONCEPT_) or [Learn about this error](https://respec.org/docs/#error-term-not-found).
. Occurred 1 times at:
[<a>](/manifest/index.html#respec-offender-no-matching-definition-found) element

There's some weirdness with resolving service-workers but also, SERVICE-WORKERS-1 ... makes a mess.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #5224

`getSpecContext()` in `xref.js` only lowercased spec names from `data-cite` attributes — it did no version-suffix normalization. So `data-cite="SERVICE-WORKERS-1"` became `service-workers-1`, which the xref API couldn't match via its `shortname` field (`service-workers`).

The fix expands each versioned spec name (matching `-\d+$`) to include both the original and the unversioned form in the same priority level. This preserves the versioned form for correct biblio resolution while also enabling shortname matching on the server.

Additionally, the "term not found" error hint now shows the raw `data-cite` value when the failing element has a local `data-cite` ancestor, so authors can spot spec shortname typos immediately.

### CODE REVIEW

**Review by sidvishnoi — COMMENTED** [review]
Concern: what if xref data has a term defined in both versoned spec and non-versioned? Can lead to "ambiguous dfn" errors.
It might not be the case, but worth checking the data and adding a test for.

File: src/core/xref.js [hunk 1]
```diff
@@ -500,7 +525,13 @@ function showErrors({ ambiguous, notFound }) {
     const originalTerm = getTermFromElement(elems[0]);
     const formUrl = getPrefilledFormURL(originalTerm, query);
     const specsString = joinAnd(specs, s => `**[${s}]**`);
-    const hint = howToFix(formUrl, originalTerm);
+    let hint = howToFix(formUrl, originalTerm);
+    /** @type {HTMLElement | null} */
+    const closestCite = elems[0].closest("[data-cite]");
+    if (closestCite && closestCite !== document.body) {
+      const citeAttr = (closestCite.dataset.cite ?? "").replace(/`/g, "");
+      hint += ` A parent element has \`data-cite="${citeAttr}"\` — check that the spec shortname is correct.`;
```
[the remark this answers is not in the document]
Comment (marcoscaceres) [reply src/core/xref.js]: This thread was resolved without a reply comment. Reviewing whether the concern was addressed in subsequent commits. Leaving this reply for traceability — Copilot should re-verify whether this was properly fixed.

**Comment by marcoscaceres** [comment]
@copilot Can you confirm all your feedback has been addressed? Can you fix anything that was not addressed?

**Comment by marcoscaceres** [comment]
@sidvishnoi Your concern is addressed in commit be15aa2. The unversioned form (e.g. `service-workers` for `service-workers-1`) is now added as a **separate lower-priority fallback level** in the spec context chain, not at the same level as the versioned form. The xref server only tries the unversioned shortname when the versioned one yields no result — so both can coexist in the data without triggering ambiguous-dfn errors.

`dedupeSpecContext` was also updated to track all previously-seen specs across levels (not just the immediate previous), preventing duplicates when the unversioned form appears elsewhere in the context chain.

A test was added to verify no "ambiguous" or "not found" errors are raised when using versioned spec names in `data-cite`.

File: src/core/xref.js [hunk 2]
```diff
@@ -229,6 +244,20 @@ function getSpecContext(elem) {
...
+      // at a lower priority so the server only falls back to them when the
+      // versioned name yields no result.  This prevents ambiguous-dfn errors if
+      // a term is indexed under both shortname variants.
+      const unversioned = [
+        ...new Set(
+          cites
+            .map(stripVersionSuffix)
+            .filter((stripped, i) => stripped !== cites[i])
+        ),
+      ];
```
Comment (sidvishnoi) [inline src/core/xref.js]: Looks like a use-case for [`Set.difference`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference).

**Review by sidvishnoi — COMMENTED** [review]
Will review again in detail...

File: src/core/xref.js (hunk 2 above)
Comment (marcoscaceres) [reply src/core/xref.js]: Applied — both occurrences in `getSpecContext` now use `Set.difference` to compute the unversioned fallback specs:

```js
const unversioned = [
  ...new Set(cites.map(stripVersionSuffix)).difference(new Set(cites)),
];
```

Much cleaner than the `.map().filter()` + positional index approach. Thanks for the suggestion!

File: src/core/xref.js [hunk 3]
```diff
@@ -242,9 +267,20 @@ function getSpecContext(elem) {
...
+      ...new Set([...bibrefs].map(el => el.textContent.toLowerCase())),
+    ];
+    if (inlineRefList.length) {
+      specs.push(inlineRefList);
+      // Same versioned → unversioned fallback for inline bibrefs.
+      const unversioned = [
+        ...new Set(inlineRefList.map(stripVersionSuffix)).difference(
+          new Set(inlineRefList)
+        ),
+      ];
```
Comment (sidvishnoi) [inline src/core/xref.js]: Nit: consider moving this into a small util function (within this file, as used twice).

File: src/core/xref.js [hunk 4]
```diff
@@ -260,11 +296,11 @@ function getSpecContext(elem) {
...
   const unique = [];
+  /** @type {Set<string>} tracks all specs seen in higher-priority levels */
+  const seen = new Set();
   for (const level of specs) {
-    const higherPriority = unique[unique.length - 1] || [];
-    const uniqueSpecs = [...new Set(level)].filter(
-      spec => !higherPriority.includes(spec)
-    );
+    const uniqueSpecs = [...new Set(level)].filter(spec => !seen.has(spec));
+    uniqueSpecs.forEach(s => seen.add(s));
```
Comment (sidvishnoi) [inline src/core/xref.js]: If we're ok with some more recent JS support, we can call `.filter` iterator directly on `Set.values()` (without converting it to array). I think we did it already in some other PR.

**Review by sidvishnoi — APPROVED** [review]

File: src/core/xref.js (hunk 3 above)
Comment (marcoscaceres) [reply src/core/xref.js]: Applied in db12c058: extracted `getUnversionedFallbacks(specs)` util used by both call sites.

File: src/core/xref.js (hunk 4 above)
Comment (marcoscaceres) [reply src/core/xref.js]: Applied in db12c058: `dedupeSpecContext` now uses `new Set(level).values().filter(s => !seen.has(s))` directly instead of spreading to array first.
